services:
  - type: web
    name: miproyecreto-backend
    env: dotnet
    region: ohio
    plan: free
    rootDir: BackendApi
    buildCommand: dotnet build -c Release && dotnet publish -c Release -o out
    startCommand: dotnet out/BackendApi.dll